/* GLCD RGB color definitions */
#define BLK           0x0000			/*   0,   0,   0 */
#define DGR       		0x03E0      /*   0, 128,   0 */
#define GRE           0x07E0      /*   0, 255,   0 */
#define WHT           0xFFFF      /* 255, 255, 255 */
#define RED           0xF800      /* 255,   0,   0 */

//Apple: Red + Green stem

unsigned short sprite_apple[] = {
WHT, WHT, WHT, WHT, GRE, GRE, GRE, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, GRE, GRE, GRE, GRE, WHT, GRE, GRE, WHT, WHT, RED, RED, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRE, RED, RED, RED, RED, RED, RED, WHT, WHT, 
WHT, RED, RED, RED, RED, RED, RED, GRE, RED, RED, RED, RED, RED, RED, RED, WHT, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, WHT, 
WHT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, WHT, 
WHT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, WHT, WHT, 
WHT, WHT, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, WHT, WHT, WHT, 
WHT, WHT, WHT, RED, RED, RED, RED, RED, RED, RED, RED, RED, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, RED, RED, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT
};

//Head: Dark Green
unsigned short sprite_head[] = {
WHT, WHT, WHT, WHT, WHT, WHT, WHT, DGR, DGR, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, WHT, 
WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, 
WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, 
WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, 
WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, 
DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, 
DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, 
WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, 
WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, 
WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, 
WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, 
WHT, WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, DGR, DGR, DGR, DGR, DGR, DGR, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, DGR, DGR, WHT, WHT, WHT, WHT, WHT, WHT, WHT
};

//body and tail Black
unsigned short sprite_body [] = {
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, 
WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, 
WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, 
WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT 
};

//white GB
unsigned short sprite_empty [] = {
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT,
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, 
WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT
};

